config/routes.rb
Rails.application.routes.draw do

  resources :user_sessions
  get 'login' =>  'user_sessions#new', :as => :login

  post 'logout' => 'user_sessions#destroy', as: :logout
  resources :users
  # devise_for :users, controllers: {
  #    sessions: 'users/sessions', registrations: 'users/registrations'
  # }

  get 'auth/login'

  get 'auth/logout'

  root to: "posts#index"

  resources :profiles

  resources :posts do
  	resources :qualifications do 
  	end
  	resources :experiences do
  	end
  	resources :projects do
  	end
  	resources :recommendations do
  	end
  end

  #devise_for :users, :controllers => {sessions: 'sessions', registrations: 'registrations'}
   
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/experience.rb
class Experience < ApplicationRecord
	belongs_to :post
	#validates :post_id, presence: true
end

app/models/other.rb
class Other < ApplicationRecord
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
	has_many :projects, dependent: :destroy
	has_many :qualifications, dependent: :destroy
	has_many :recommendations, dependent: :destroy
	has_many :experiences, dependent: :destroy
	has_many :others, dependent: :destroy
	has_many :skills, dependent: :destroy 
	belongs_to :post
	validates :first_name, :last_name, :category, :about, presence: true

	has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  	validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/


	accepts_nested_attributes_for :projects, :recommendations, :experiences, :qualifications, :skills, :others, allow_destroy: true

	EMAIL_REGEX = /\A[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,4}\Z/i
	validates :email, 
	:presence => true,
	:length => { :maximum => 100 },
	:format => EMAIL_REGEX,
	:confirmation => true

	def full_name
		"#{self.first_name} #{self.last_name}"
		
	end
	
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :post
  #validates :post_id, presence: true
end

app/models/qualification.rb
class Qualification < ApplicationRecord
  belongs_to :post

  #validates :post_id, presence: true
end

app/models/recommendation.rb
class Recommendation < ApplicationRecord
	belongs_to :post
	#validates :post_id, presence: true
end

app/models/skill.rb
class Skill < ApplicationRecord
  belongs_to :post
end

app/models/user.rb
class User < ApplicationRecord
  authenticates_with_sorcery!
  has_one :post
  EMAIL_REGEX = /\A[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,4}\Z/i

  validates :password, length: {minimum: 3}, if: -> {new_record? || changes[:crypted_password]}
  validates :password, confirmation: true , if: -> {new_record? || changes[:crypted_password]}
  validates :password_confirmation, presence: true, if: -> {new_record? || changes[:crypted_password]}
  validates :email, 
	:presence => true,
	uniqueness: true,
	:length => { :maximum => 100 },
	:format => EMAIL_REGEX,
	:confirmation => true


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  #after_filter :flash_to_headers
  
  private

    # def flash_to_headers
    #   return unless request.xhr?
    #   response.headers['X-Message'] = flash_message
    #   response.headers["X-Message-Type"] = flash_type.to_s

    #   flash.discard # don't want the flash to appear when you reload page
    # end

    # def flash_message
    #   [:error, :warning, :notice].each do |type|
    #     return flash[type] unless flash[type].blank?
    #   end
    # end

    # def flash_type
    #   [:error, :warning, :notice].each do |type|
    #     return type unless flash[type].blank?
    #   end
    # end

    # app/controllers/application_controller.rb
    
    def not_authenticated
        redirect_to login_path, alert: "Please login first"
    end

    
end

app/controllers/auth_controller.rb
class AuthController < ApplicationController
  def login
  end

  def logout
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  #layout 'cv', only: [:show]
  layout 'form', only: [:new, :edit]
  before_action :require_login, only: [:edit, :update]
	before_action :get_post, only: [:edit, :show, :delete, :update, :destroy]
  
  def index
  	@posts = Post.all
    if current_user and current_user.post
      @post = current_user.post
      #render :show, layout: 'cv'
    end
    
  end

  def edit
  	
  end

  def update
    if @post.update_attributes(post_params)
      redirect_to post_path @post
    else
      render "edit"
    end
  end


  def show
    render :show, layout: 'cv'
  end

  def new
  	@post = Post.new
  end

  def destroy
  	@post.destroy
  	redirect_to posts_path
  end
  

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id if current_user
  	if @post.save
      flash[:notice] = "Post created successfully"
      redirect_to post_path @post
    else
      render new_post_path
    end
  end

  private
  def post_params
  	params.require(:post).permit(:first_name, :last_name, :email, :category, :about, :avatar,
      qualifications_attributes: [:id, :post_id, :school, :detail, :grad_yr, :degree, :_destroy], 
      projects_attributes: [:id, :post_id, :name, :project_yr, :description, :_destroy],
       experiences_attributes: [:id, :post_id, :place, :position , :detail, :work_start, :work_end, :current_work, :_destroy], 
       recommendations_attributes: [:id, :name, :position, :email, :post_id, :_destroy],
       others_attributes: [:id, :post_id, :title, :detail],
       skills_attributes: [:id, :post_id, :talent])
  end

  def get_post
  	@post = Post.find(params[:id])
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
	#layout one
	def index
		
	end

	def show
		@user = User.find(params[:id])
	end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  def new
  	@user =  User.new
  end

  def create
  	if @user = login(params[:email], params[:password])
  		redirect_back_or_to(request.referrer, notice: 'Login Successful')
  	else
  		flash.now[:alert] = 'Login Failed'
      #byebug
  		render  json: {message: 'Password or Email Invalid'} , status: 401
  	end
  end

  def destroy
  	logout
  	redirect_to(request.referrer, notice: 'Logout!')
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

      if @user.save
        auto_login(@user)

        redirect_to request.referrer, notice: 'User was successfully created.'
        #render :show, status: :created, location: @user }
      else
        render json: @user.errors.full_messages, status: :unprocessable_entity 
      end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    logout
    redirect_to root_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/helpers/auth_helper.rb
module AuthHelper
end

app/helpers/posts_helper.rb
module PostsHelper

	def link_to_add_fields(text, f, assoc)
		new_obj = f.object.send(assoc).klass.new
		id =new_obj.object_id
		fields = f.fields_for(assoc, new_obj, child_index: id ) do |builder| 
			render assoc.to_s + "_fields", builder: builder
		end
		link_to( text, '#', class: "add_fields btn  btn-simple btn-primary", data: {id: id, field: fields.gsub('\n', '')}) 

		
	end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/experiences/_experience.html.erb
				<article>
					<h2><%= experience.position %> </h2>
					<h3><%= experience.place %> </h3>
					<p class="subDetails"> <%= experience.work_start %> - <%=experience.work_end %></p>
					<p><%= experience.detail %></p>
				</article>

app/views/others/_other.html.erb
<section>
			<div class="sectionTitle">
				<h1><%=  other.title %></h1>
			</div>
			
			<div class="sectionContent">
			<%= other.detail %>
			</div>
			<div class="clear"></div>
</section>

app/views/posts/_experiences_fields.html.erb
<fieldset>
<div class="row">

        <div class="col-sm-7 col-sm-offset-1">
                <div class="form-group label-floating">
                        <label class="control-label">Place Of Work</label>
                        <%= builder.input :place, label: false, class: 'form-control' %>
                </div>
        </div>
        <div class="col-sm-3">
                <div class="form-group label-floating">
                        <label class="control-label">Position</label>
                        <%= builder.input :position, label: false, class: 'form-control' %>
                </div>
        </div>
        <div class="col-sm-3 col-sm-offset-1">
                <div class="form-group label-floating">
                        <label class="control-label">Work Start</label>
                        <%= builder.input :work_start, label: false, class: 'form-control' %>
                </div>
        </div>
        <div class="col-sm-3 col-sm-offset-1">
                <div class="form-group label-floating">
                        <label class="control-label">Work End</label>
                        <%= builder.input :work_end, label: false, class: 'form-control' %>
                </div>
        </div>
        <div class="col-sm-3 col-sm-offset-1">
                <div class="form-group label-floating">
                        <label class="control-label">Cirrent Work?</label>
                        <%= builder.input :current_work, label: false, class: 'form-control' %>
                </div>
        </div>
        <div class="col-sm-5">
                <div class="form-group label-floating">
                        <label class="control-label">Further Comment</label>
                        <%= builder.input :detail, label: false, class: 'form-control' %>
                </div>
        </div>
        <%= builder.hidden_field :_destroy  %>
        
                <%= link_to   "#", class:  "remove_fields btn btn-simple btn-danger" do %>
                Remove<div class="ripple-container"></div>
        <% end %>        
</div>
</fieldset>
                

app/views/posts/_form.html.erb
 <%= simple_form_for post do |f| %>
 <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<table summary="Post form fields">
      <tr>
        <%= f.input :first_name, label: "First Name", error: "First Name is mandatory"%>

      </tr>
      <tr>
        <%= f.input :last_name, label: "Last Name", error: "Last Name is mandatory"%>
      </tr>
      <tr>
           <%= f.input :email, placeholder: "user@domain.com"%>   
      </tr>
      <tr>
        <%= f.input :category, label: "Category of Work"%>
      </tr>
            <tr>
        <%= f.input :about, label: "Say Something About Yourself"%>
      </tr>

      <%= f.fields_for :qualifications do |builder| %>
         <%= render 'qualifications_fields', builder: builder %>

      <% end %>
      <%= link_to_add_fields "Add Qualification", f, :qualifications %>

      <%= f.fields_for :skills do |builder| %>
         <%= render 'skills_fields', builder: builder %>

      <% end %>
      <%= link_to_add_fields "Add Skill", f, :skills %>

      <%= f.fields_for :projects do |builder| %>
 
       <%= render 'projects_fields', builder: builder %>

       
      <% end %>
      <%= link_to_add_fields "Add Project", f, :projects %>


      <%= f.fields_for :experiences do |builder| %>

       <%= render 'experiences_fields', builder: builder %>





      <% end %>
      <%= link_to_add_fields "Add Experience", f , :experiences%>


      <%= f.fields_for :recommendations do |builder| %>

       <%= render 'recommendations_fields', builder: builder %>

      <% end %>
      <%= link_to_add_fields "Add Recommendation", f, :recommendations %>

      <%= f.fields_for :others do |builder| %>
         <%= render 'others_fields', builder: builder %>

      <% end %>
      <%= link_to_add_fields "Add Other", f, :others %>

      <%= f.submit "Create CV" %>

</table>

<% end %>

app/views/posts/_new_form.html.erb
<!--   Big container   -->
<div class="container">
	<div class="row">
		<div class="col-sm-8 col-sm-offset-2">
			<!--      Wizard container        -->
			<div class="wizard-container">
				<div class="card wizard-card" data-color="purple" id="wizardProfile">
				<%=  render 'actual_form', post: post %>
				</div>
			</div> <!-- wizard container -->
		</div>
	</div><!-- end row -->
</div> 

app/views/posts/_others_fields.html.erb
        <fieldset>
<div class="row">

	<div class="col-sm-3 col-sm-offset-1">
		<div class="form-group label-floating">
			<label class="control-label">Title</label>
			<%= builder.input :title, label: false, class: 'form-control' %>
		</div>
	</div>
	<div class="col-sm-8">
		<div class="form-group label-floating">
			<label class="control-label">Description</label>
			<%= builder.input :detail, label: false, class: 'form-control' %>
		</div>
	</div>
	<%= builder.hidden_field :_destroy  %>
	
			<%= link_to   "#", class:  "remove_fields btn btn-simple btn-danger" do %>
		Remove<div class="ripple-container"></div>
	<% end %></div>
</fieldset>

app/views/posts/_personal_info.html.erb
		<div class="tab-pane" id="about">
			<div class="row">
				<h4 class="info-text"> Let's start with your basic information</h4>
				<div class="col-sm-4 col-sm-offset-1">
					<div class="picture-container">
						<div class="picture">
							
							<%= image_tag 'cv/default-avatar.png', class: 'picture-src', id: 'wizardPicturePreview'%>
							<%= f.input :avatar, id: 'wizard-picture', label: false %>
						</div>
						<h6>Choose Picture</h6>
					</div>
				</div>
				<div class="col-sm-6">
					<div class="input-group">
						<span class="input-group-addon">
							<i class="material-icons">face</i>
						</span>
						<div class="form-group label-floating">
							<label class="control-label">First Name <small>(required)</small></label>
							<%= f.input :first_name, label: false , class: "form-control", error: "First Name is mandatory"%>

						</div>
					</div>

					<div class="input-group">
						<span class="input-group-addon">
							<i class="material-icons">record_voice_over</i>
						</span>
						<div class="form-group label-floating">
							<label class="control-label">Last Name <small>(required)</small></label>
							<%= f.input :last_name, label: false , class: "form-control", error: "Last Name is mandatory"%>
						</div>
					</div>
				</div>
				<div class="col-sm-10 col-sm-offset-1">
					<div class="input-group">
						<span class="input-group-addon">
							<i class="material-icons">email</i>
						</span>
						<div class="form-group label-floating">
							<label class="control-label">Email <small>(required)</small></label>
							<%= f.input :email, label: false , class: "form-control", error: "Email is mandatory"%>
						</div>
					</div>
				</div>
				<div class="col-sm-10 col-sm-offset-1">
					<div class="input-group">
						<span class="input-group-addon">
							<i class="material-icons">assignment</i>
						</span>
						<div class="form-group label-floating">
							<label class="control-label">Category <small>(required)</small></label>
							<%= f.input :category, label: false , class: "form-control", error: "Category is mandatory"%>
						</div>
					</div>
				</div>

				<div class="col-sm-10 col-sm-offset-1">
					<div class="input-group">
						<span class="input-group-addon">
							<i class="material-icons">bookmark</i>
						</span>
						<div class="form-group label-floating">
							<label class="control-label">Say something about yourself <small>(required)</small></label>
							<%= f.input :about, label: false , class: "form-control", error: "Profile is mandatory"%>
						</div>
					</div>
				</div>

			</div>
		</div>

app/views/posts/_projects.html.erb
		<div class="tab-pane text-center" id="projects">

			<div class="row">
				<div class="col-sm-12">
		 			<h4 class="info-text"> Projects You Participated In </h4>
		 		</div>

			</div>
		 		<%= f.fields_for :projects do |builder| %>
         			<%= render 'projects_fields', builder: builder %>

      			<% end %>
		
				<%= link_to_add_fields "New Project", f, :projects %>
			
		</div>

app/views/posts/_projects_fields.html.erb
 <fieldset>
<div class="row">

	<div class="col-sm-7 col-sm-offset-1">
		<div class="form-group label-floating">
			<label class="control-label">Project Title</label>
			<%= builder.input :name, label: false, class: 'form-control' %>
		</div>
	</div>
	<div class="col-sm-3">
		<div class="form-group label-floating">
			<label class="control-label">Project Year</label>
			<%= builder.input :project_yr, label: false, class: 'form-control' %>
		</div>
	</div>
	<div class="col-sm-8 col-sm-offset-1">
		<div class="form-group label-floating">
			<label class="control-label">Describe Project</label>
			<%= builder.input :description, label: false, class: 'form-control' %>
		</div>
	</div>
	<%= builder.hidden_field :_destroy  %>
	
			<%= link_to   "#", class:  "remove_fields btn btn-simple btn-danger" do %>
		Remove<div class="ripple-container"></div>
	<% end %>	
</div>
</fieldset>

app/views/posts/_qualifications.html.erb
		<div class="tab-pane text-center" id="education">

			<div class="row">
				<div class="col-sm-12">
		 			<h4 class="info-text"> Education Details </h4>
		 		</div>
		 		
			</div>
			<%= f.fields_for :qualifications do |builder| %>
         			<%= render 'qualifications_fields', builder: builder %>

      			<% end %>
			
				<%= link_to_add_fields "New Education", f, :qualifications %>
			
		</div>

app/views/posts/_qualifications_fields.html.erb
<fieldset>
<div class="row">

	<div class="col-sm-7 col-sm-offset-1">
		<div class="form-group label-floating">
			<label class="control-label">School Name</label>
			<%= builder.input :school, label: false, class: 'form-control' %>
		</div>
	</div>
	<div class="col-sm-3">
		<div class="form-group label-floating">
			<label class="control-label">Graduation Year</label>
			<%= builder.input :grad_yr, label: false, class: 'form-control' %>
		</div>
	</div>
	<div class="col-sm-5 col-sm-offset-1">
		<div class="form-group label-floating">
			<label class="control-label">Degree</label>
			<%= builder.input :degree, label: false, class: 'form-control' %>
		</div>
	</div>
	<div class="col-sm-5">
		<div class="form-group label-floating">
			<label class="control-label">Further Comment</label>
			<%= builder.input :detail, label: false, class: 'form-control' %>
		</div>
	</div>
	<%= builder.hidden_field :_destroy  %>
	
			<%= link_to  "#", class:  "remove_fields btn btn-simple btn-danger" do %>
		 			Remove<div class="ripple-container"></div>
	<% end %>	
</div>
</fieldset>

app/views/posts/_recommendations.html.erb
		<div class="tab-pane text-center" id="recommendations">

			<div class="row">
				<div class="col-sm-12">
		 			<h4 class="info-text"> Recommendations </h4>
		 		</div>
		 		
			</div>
			<%= f.fields_for :recommendations do |builder| %>
         			<%= render 'recommendations_fields', builder: builder %>

      			<% end %>
			
				<%= link_to_add_fields "New Recommendation", f, :recommendations %>
			
		</div>

app/views/posts/_recommendations_fields.html.erb
<fieldset>
<div class="row">

	<div class="col-sm-7 col-sm-offset-1">
		<div class="form-group label-floating">
			<label class="control-label">Name</label>
			<%= builder.input :name, label: false, class: 'form-control' %>
		</div>
	</div>
	<div class="col-sm-3">
		<div class="form-group label-floating">
			<label class="control-label">Position</label>
			<%= builder.input :position, label: false, class: 'form-control' %>
		</div>
	</div>
	<div class="col-sm-5 col-sm-offset-1">
		<div class="form-group label-floating">
			<label class="control-label">Email</label>
			<%= builder.input :email, label: false, class: 'form-control' %>
		</div>
	</div>
	<%= builder.hidden_field :_destroy  %>
	
			<%= link_to   "#", class:  "remove_fields btn btn-simple btn-danger" do %>
		Remove<div class="ripple-container"></div>
	<% end %>	
</div>
</fieldset>

app/views/posts/_skills.html.erb
		<div class="tab-pane text-center" id="skills">

			<div class="row">
				<div class="col-sm-12">
		 			<h4 class="info-text"> Your Professional Skills </h4>
		 		</div>

			</div>
			<%= f.fields_for :skills do |builder| %>
         			<%= render 'skills_fields', builder: builder %>

      			<% end %>
			
				<%= link_to_add_fields "New Skills", f, :skills %>
			
		</div>

app/views/posts/_skills_fields.html.erb
<fieldset>
<div class="row">

	<div class="col-sm-7 col-sm-offset-1">
		<div class="form-group label-floating">
			<label class="control-label">Skill</label>
			<%= builder.input :talent, label: false, class: 'form-control' %>
		</div>
	</div>

	<%= builder.hidden_field :_destroy  %>
	
	<%= link_to   "#", class:  "remove_fields btn btn-simple btn-danger" do %>
		Remove<div class="ripple-container"></div>
	<% end %>

</div>
</fieldset>

app/views/posts/index.html.erb
    <div class="main main-raised">
      <div class="container">
          <div class="section text-center section-landing">
                  <div class="row">
                      <div class="col-md-8 col-md-offset-2">
                          <h2 class="title">A Simple Resume Creator</h2>
                          <h5 class="description"> Get your own customized resume. Fill a form and get your own personal link to share your resume with your friends, employees etc </h5>
                      </div>
                  </div>

          <div class="features">
            <div class="row">
                        <div class="col-md-4">
                <div class="info">
                  <div class="icon icon-primary">
                    <i class="material-icons">chat</i>
                  </div>
                  <h4 class="info-title">Likes & Views</h4>
                  <p>Get feedback on what people think about your resume. See how many people have viewed it and how many 'liked' it. </p>
                </div>
                        </div>
                        <div class="col-md-4">
                <div class="info">
                  <div class="icon icon-success">
                    <i class="material-icons">verified_user</i>
                  </div>
                  <h4 class="info-title">Information Verification</h4>
                  <p>Send proof to our team and get your education details verified</p>
                </div>
                        </div>
                        <div class="col-md-4">
                <div class="info">
                  <div class="icon icon-danger">
                    <i class="material-icons">fingerprint</i>
                  </div>
                  <h4 class="info-title">PDF Download</h4>
                  <p>Get PDF Versions of your resume with just one click. We can also get it emailed to you if you want that. </p>
                </div>
                        </div>
                    </div>
          </div>
              </div>







              </div>
          </div>

    </div>

app/views/profiles/index.html.erb
Here man

app/views/profiles/show.html.erb
		<div class="header header-filter" style="background-image: url('../assets/img/examples/city.jpg');"></div>

		<div class="main main-raised">
			<div class="profile-content">
	            <div class="container">
	                <div class="row">
	                    <div class="profile">
	                        <div class="avatar">
	                            <%= image_tag 'headshot.jpg', alt:"Circle Image" , class: "img-circle img-responsive img-raised"%>
	                        </div>
	                        <div class="name">
	                            <h3 class="title"><%= @user.post.full_name %></h3>
								<h6><%= @user.post.category if @user.post %></h6>
	                        </div>
	                    </div>
	                </div>
	                <div class="description text-center">
                        <p><%= @user.post.about if @user.post %> </p>
	                </div>

					<div class="row">
						<div class="col-md-6 col-md-offset-3">
							<div class="profile-tabs">
			                    <div class="nav-align-center">
									<ul class="nav nav-pills" role="tablist">
										<li class="active">
											<a href="#studio" role="tab" data-toggle="tab">
												<i class="material-icons">camera</i>
												View CV
											</a>
										</li>
										<li>
				                            <a href="#work" role="tab" data-toggle="tab">
												<i class="material-icons">palette</i>
												Download PDF
				                            </a>
				                        </li>
				                       
				                    </ul>
								</div>
							</div>
							<!-- End Profile Tabs -->
						</div>
	                </div>

	            </div>
	        </div>
		</div>

    

app/views/qualifications/_qualification.html.erb
<article>
					<h2><%= qualification.school %></h2>
					<h3> <%= qualification.degree %></h3>
					<p class="subDetails">Qualification</p>
					<p><%= qualification.detail %></p>
				</article>

app/views/recommendations/_recommendation.html.erb
<article>
					<h2><%= recommendation.name %></h2>
					<h3> <%= recommendation.position %></h3>
					<h3> <%= recommendation.email %></h3>
					<p class="subDetails"></p>
					<p></p>
				</article>

app/views/skills/_skill.html.erb
<li><%= skill.talent %></li>

app/views/user_sessions/_form.html.erb
<%= form_tag user_sessions_path, method: :post do %>
<%= label_tag :email %>
<%= text_field_tag :email %>
<%= label_tag :password %>
<%= password_field_tag :password %>
<%= submit_tag 'Login' %>
<% end %>

app/views/user_sessions/new.html.erb
<h1>login</h1>

<%= render 'form' %>

app/views/users/_form.html.erb
<%= simple_form_for(@user) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :email %>
    <%= f.input :password %>
    <%= f.input :password_confirmation %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>

      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>

        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>



<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>