config/routes.rb
Rails.application.routes.draw do

  resources :user_sessions
  get 'login' =>  'user_sessions#new', :as => :login

  post 'logout' => 'user_sessions#destroy', as: :logout
  resources :users
  # devise_for :users, controllers: {
  #    sessions: 'users/sessions', registrations: 'users/registrations'
  # }

  get 'auth/login'

  get 'auth/logout'

  root to: "posts#index"

  resources :profiles

  resources :posts do
  	resources :qualifications do 
  	end
  	resources :experiences do
  	end
  	resources :projects do
  	end
  	resources :recommendations do
  	end
  end

  #devise_for :users, :controllers => {sessions: 'sessions', registrations: 'registrations'}
   
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/experience.rb
class Experience < ApplicationRecord
	belongs_to :post
	#validates :post_id, presence: true
end

app/models/other.rb
class Other < ApplicationRecord
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
	has_many :projects, dependent: :destroy
	has_many :qualifications, dependent: :destroy
	has_many :recommendations, dependent: :destroy
	has_many :experiences, dependent: :destroy
	has_many :others, dependent: :destroy
	has_many :skills, dependent: :destroy 
	belongs_to :post
	validates :first_name, :last_name, :category, :about, presence: true

	has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  	validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/


	accepts_nested_attributes_for :projects, :recommendations, :experiences, :qualifications, :skills, :others, allow_destroy: true

	EMAIL_REGEX = /\A[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,4}\Z/i
	validates :email, 
	:presence => true,
	:length => { :maximum => 100 },
	:format => EMAIL_REGEX,
	:confirmation => true

	def full_name
		"#{self.first_name} #{self.last_name}"
		
	end
	
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :post
  #validates :post_id, presence: true
end

app/models/qualification.rb
class Qualification < ApplicationRecord
  belongs_to :post

  #validates :post_id, presence: true
end

app/models/recommendation.rb
class Recommendation < ApplicationRecord
	belongs_to :post
	#validates :post_id, presence: true
end

app/models/skill.rb
class Skill < ApplicationRecord
  belongs_to :post
end

app/models/user.rb
class User < ApplicationRecord
  authenticates_with_sorcery!
  has_one :post
  EMAIL_REGEX = /\A[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,4}\Z/i

  validates :password, length: {minimum: 3}, if: -> {new_record? || changes[:crypted_password]}
  validates :password, confirmation: true , if: -> {new_record? || changes[:crypted_password]}
  validates :password_confirmation, presence: true, if: -> {new_record? || changes[:crypted_password]}
  validates :email, 
	:presence => true,
	uniqueness: true,
	:length => { :maximum => 100 },
	:format => EMAIL_REGEX,
	:confirmation => true


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  #after_filter :flash_to_headers
  
  private

    # def flash_to_headers
    #   return unless request.xhr?
    #   response.headers['X-Message'] = flash_message
    #   response.headers["X-Message-Type"] = flash_type.to_s

    #   flash.discard # don't want the flash to appear when you reload page
    # end

    # def flash_message
    #   [:error, :warning, :notice].each do |type|
    #     return flash[type] unless flash[type].blank?
    #   end
    # end

    # def flash_type
    #   [:error, :warning, :notice].each do |type|
    #     return type unless flash[type].blank?
    #   end
    # end

    # app/controllers/application_controller.rb
    
    def not_authenticated
        redirect_to login_path, alert: "Please login first"
    end

    
end

app/controllers/auth_controller.rb
class AuthController < ApplicationController
  def login
  end

  def logout
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  #layout 'cv', only: [:show]
  layout 'form', only: [:new, :edit]
  before_action :require_login, only: [:edit, :update]
	before_action :get_post, only: [:edit, :show, :delete, :update, :destroy]
  
  def index
  	@posts = Post.all
    if current_user and current_user.post
      @post = current_user.post
      #render :show, layout: 'cv'
    end
    
  end

  def edit
  	
  end

  def update
    if @post.update_attributes(post_params)
      redirect_to post_path @post
    else
      render "edit"
    end
  end


  def show
    render :show, layout: 'cv'
  end

  def new
  	@post = Post.new
  end

  def destroy
  	@post.destroy
  	redirect_to posts_path
  end
  

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id if current_user
  	if @post.save
      flash[:notice] = "Post created successfully"
      redirect_to post_path @post
    else
      render new_post_path
    end
  end

  private
  def post_params
  	params.require(:post).permit(:first_name, :last_name, :email, :category, :about, :avatar,
      qualifications_attributes: [:id, :post_id, :school, :detail, :grad_yr, :degree, :_destroy], 
      projects_attributes: [:id, :post_id, :name, :project_yr, :description, :_destroy],
       experiences_attributes: [:id, :post_id, :place, :position , :detail, :work_start, :work_end, :current_work, :_destroy], 
       recommendations_attributes: [:id, :name, :position, :email, :post_id, :_destroy],
       others_attributes: [:id, :post_id, :title, :detail],
       skills_attributes: [:id, :post_id, :talent])
  end

  def get_post
  	@post = Post.find(params[:id])
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
	#layout one
	def index
		
	end

	def show
		@user = User.find(params[:id])
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

      if @user.save
        auto_login(@user)

        redirect_to request.referrer, notice: 'User was successfully created.'
        #render :show, status: :created, location: @user }
      else
        render json: @user.errors.full_messages, status: :unprocessable_entity 
      end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    logout
    redirect_to root_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/helpers/auth_helper.rb
module AuthHelper
end

app/helpers/posts_helper.rb
module PostsHelper

	def link_to_add_fields(text, f, assoc)
		new_obj = f.object.send(assoc).klass.new
		id =new_obj.object_id
		fields = f.fields_for(assoc, new_obj, child_index: id ) do |builder| 
			render assoc.to_s + "_fields", builder: builder
		end
		link_to( text, '#', class: "add_fields btn  btn-simple btn-primary", data: {id: id, field: fields.gsub('\n', '')}) 

		
	end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
	    <footer class="footer">
	        <div class="container">
	            <nav class="pull-left">
	                <ul>
	                    <li>
	                        <a href="#">
	                            Material Resume
	                        </a>
	                    </li>

	                </ul>
	            </nav>
	            <div class="copyright pull-right">
	                &copy; 2017, made with <i class="fa fa-heart heart"></i> by Material Resume
	            </div>
	        </div>
	    </footer>

app/views/layouts/_header.html.erb
<div class="header header-filter landing-header">
    <div class="container">
      <div class="row">
        <div class="col-md-6">
          <h1 class="title">Material Resume</h1>
          <h4>Want a resume? Get one without much stress. And take advantage of our beautiful material design forms.</h4>
          <br />
          <% if current_user %>
          <%= link_to  new_post_path,  class: "btn btn-danger btn-raised btn-lg" do %>
          <i class="fa fa-play"></i>  Create Your Resume
          <% end %>
          <% else %>
          <%= link_to  "javascript:void(0)", id: "reg-warn", class: "btn btn-danger btn-raised btn-lg" do %>
          <i class="fa fa-play"></i>  Create Your Resume
          <% end %>

          <% end %>

          
        </div>
      </div>
    </div>
  </div>

app/views/layouts/_nav.html.erb
    <nav class="navbar   navbar-fixed-top navbar-color-on-scroll">
    	<div class="container">
        	<!-- Brand and toggle get grouped for better mobile display -->
        	<div class="navbar-header">
        		<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navigation-example">
            		<span class="sr-only">Toggle navigation</span>
		            <span class="icon-bar"></span>
		            <span class="icon-bar"></span>
		            <span class="icon-bar"></span>
        		</button>
                <%= link_to  'Material Resume', root_path, class: "navbar-brand"  %>
        	</div>

        	<div class="collapse navbar-collapse" id="navigation-example">
        		<ul class="nav navbar-nav navbar-right">
                <% if current_user %>
                    <li>
                        <%= link_to  logout_path, method: :post do %>
                        <i class="material-icons">unarchive</i> Log Out
                        <% end %>
                    </li>

                    <li>
                        <%= link_to  "#"  do %>
                        <i class="material-icons">unarchive</i> Profile
                        <% end %>
                    </li>

                    

                    
                <% else %>
                    <li>
                        <%= link_to  "javascript:void(0)", class: "signup-btn" do %>
                        <i class="material-icons">perm_identity</i> Register
                        <% end %>
                    </li>
                    <li>
                        <%= link_to "javascript:void(0)", class: "signin-btn" do %>
                        <i class="material-icons">rowing</i> Log In
                        <% end %>
                    </li>
                    
                <% end %>


		            <li>
		                <a href="javascript:void(0)" target="_blank" class="btn btn-simple btn-white btn-just-icon">
							<i class="fa fa-twitter"></i>
						</a>
		            </li>
		            <li>
		                <a href="javascript:void(0)" target="_blank" class="btn btn-simple btn-white btn-just-icon">
							<i class="fa fa-facebook-square"></i>
						</a>
		            </li>
					<li>
		                <a href="javascript:void(0)" target="_blank" class="btn btn-simple btn-white btn-just-icon">
							<i class="fa fa-instagram"></i>
						</a>
		            </li>
        		</ul>
        	</div>
    	</div>
    </nav>

app/views/layouts/_popupforms.html.erb
  <!-- Modal -->
<div class="modal fade" id="signin-modal" role="dialog">
    <div class="modal-dialog">
    <%= render 'layouts/sign_in' %>
      
    </div>
</div>


<!--  -->

  <!-- Modal -->
  <div class="modal fade " id="signup-modal" role="dialog">
    <div class="modal-dialog " >
    

        
       
	          <%= render 'layouts/sign_up' %>


      
    </div>
  </div>

app/views/layouts/_register_warning.html.erb
<div  class="modal fade" id="reg-modal"  role="dialog" >
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-hidden="true">
					<i class="material-icons">clear</i>
				</button>
				<h4 class="modal-title"></h4>
			</div>
			<div class="modal-body" style="padding: 20px;">
				<h3><p> Sign up with us and get extra features. You can also come back later to edit your resume. It only takes a few seconds. No spam, pinky swear.
				</p></h3>

				<div class="row">
					<div class="col-xs-5 pull-left">
							                        
	                        
	                        <button type="button" class="btn btn-info  btn-lg signup-btn">Sign Up</button>

					</div>

					<div class="col-xs-5 col-xs-offset-2 pull-right">
						<button type="button" class="btn btn-success  btn-lg signin-btn" >Log In</button>

					</div>
					       
					</div>
				</div>

				<div class="text-center">
					<h4><p> Leave me alone. I just want a quick resume</p> </h4>
					<%= link_to  new_post_path,  class: "btn btn-danger btn-raised btn-md" do %>
          			<i class="fa fa-play"></i>  Create Resume
          				<% end %>

				</div>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-danger btn-simple" data-dismiss="modal">Close<div class="ripple-container"></div></button>
			</div>
		</div>
	</div>
</div>

app/views/layouts/_sign_in.html.erb
<div class="wrapper popup">
      <div class="container-fluid popup-dialog">

            <div class="card card-signup">
              <%= form_tag user_sessions_path, method: :post , :id => "sign_in_user", :format => :json, :remote => true  do  %>
                <div class="header header-primary text-center">
                  <h4>Log In</h4>
                  
                  
                  <div class="social-line">
                    <a href="#pablo" class="btn btn-simple btn-just-icon">
                      <i class="fa fa-facebook-square"></i>
                    </a>
                    <a href="#pablo" class="btn btn-simple btn-just-icon">
                      <i class="fa fa-twitter"></i>
                    </a>
                    <a href="#pablo" class="btn btn-simple btn-just-icon">
                      <i class="fa fa-google-plus"></i>
                    </a>
                  </div>
                </div>
                <p class="text-divider">Or Be Classical</p>

              <div id='signin-error' class = 'text-center' style = 'color: red;'> </div>
                <div class="content">

                  <div class="input-group">
                    <span class="input-group-addon">
                      <i class="material-icons">email</i> 
                    </span>
                    <div class="form-group email required ">
                    <%= email_field_tag :email, '', class: "form-control string email required" , required: true,  label: false, placeholder: 'email'%>
                    </div>
                    
                  </div>

                  <div class="input-group">
                    <span class="input-group-addon">
                      <i class="material-icons">lock_outline</i>
                    </span>
                    <div class="form-group password required ">
                    <%= password_field_tag :password, '',  class: "form-control string password required" , required: true , label: false, placeholder: 'Password'%>
                    </div>
                  </div>

                  <!-- If you want to add a checkbox to this form, uncomment this code 

                  <div class="checkbox">
                  
                  </div>  -->
                </div>
                <div class="footer text-center">
                  <%= submit_tag  "Log In",  class: "btn btn-simple btn-primary btn-lg" %>
                </div>
              <%end%>
                            <div class="text-center">
                <h5> Don't have an account? </h5>
              <button type="button" class="btn btn-info btn-simple btn-lg signup-btn">Sign Up</button>

              </div>
            </div>

          </div>


      </div>

      

app/views/layouts/_sign_up.html.erb
<div class="wrapper popup">
      <div class="container-fluid popup-dialog">

            <div class="card card-signup">
            <%=  simple_form_for :user, url: url_for(action: 'create', controller: 'users'), :html => {:id => "sign_up_user"}, :format => :json, :remote => true  do |f| %>
                <div class="header header-primary text-center">
                  <h4>Sign Up</h4>
                  
                  
                  <div class="social-line">
                    <a href="#pablo" class="btn btn-simple btn-just-icon">
                      <i class="fa fa-facebook-square"></i>
                    </a>
                    <a href="#pablo" class="btn btn-simple btn-just-icon">
                      <i class="fa fa-twitter"></i>
                    </a>
                    <a href="#pablo" class="btn btn-simple btn-just-icon">
                      <i class="fa fa-google-plus"></i>
                    </a>
                  </div>
                </div>
                <p class="text-divider">Or Be Classical</p>

              <div id='signup-error' class = 'text-center' style = 'color: red;'> </div>
                <div class="content">

                  <div class="input-group">
                    <span class="input-group-addon">
                      <i class="material-icons">email</i>
                    </span>
                    <%= f.input :email, required: true, autofocus: true , label: false, placeholder: 'email'%>
                  </div>

                  <div class="input-group">
                    <span class="input-group-addon">
                      <i class="material-icons">lock_outline</i>
                    </span>
                    <%= f.input :password, required: true, label: false, placeholder: 'Password' %>
                  </div>

                  <!-- If you want to add a checkbox to this form, uncomment this code -->

                  <div class="input-group">
                    <span class="input-group-addon">
                      <i class="material-icons">lock_outline</i>
                    </span>
                    <%= f.input :password_confirmation, required: true, label: false, placeholder: 'Confirm Password' %>
                  </div>
                </div>
                <div class="footer text-center">
                  <%= f.button :submit, "Sign Up",  class: "btn btn-simple btn-primary btn-lg" %>
                </div>
              <%end%>
       <div class="text-center">
                <h5> Already have an account? </h5>
              <button type="button" class="btn btn-info btn-simple btn-lg signin-btn">Log In</button>

              </div>
            </div>

          </div>


      </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title> Material Resume </title>
    <%=  csrf_meta_tags  %>
      <meta charset="utf-8" />
  <link rel="icon" type="image/png" href="../assets/img/favicon.png">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />

  <title>Material Resume - Create your own resume</title>

  <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0' name='viewport' />

  <!--     Fonts and icons     -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons" />
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700" />

    <%= stylesheet_link_tag    'posts', media: 'all', 'data-turbolinks-track': 'reload' %>
    
  </head>

  <body class="landing-page">
    <%= render 'layouts/popupforms' %>

    <% unless current_user %>
      <%= render 'layouts/register_warning' %>
    <% end %>
  
    <%= render 'layouts/nav' %>
    <div class="wrapper">
    <%=render 'layouts/header' %>
      <p class="notice"><%= notice %></p>
   <p class="alert"><%= alert %></p>

    <%= yield %>

      



    <%= render 'layouts/footer' %>

    








    </div>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'posts', 'data-turbolinks-track': 'reload' %>

  
  </body>
</html>

app/views/layouts/cv.html.erb
<!DOCTYPE html>
<html>
<head>
<title> - Curriculum Vitae</title>

<meta name="viewport" content="width=device-width"/>
<meta name="description" content="The Curriculum Vitae of Joe Bloggs."/>
<meta charset="UTF-8"> 
<link href='http://fonts.googleapis.com/css?family=Rokkitt:400,700|Lato:400,300' rel='stylesheet' type='text/css'>
<%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'cv/posts', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>


<!--[if lt IE 9]>
<script src="//html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->
</head>
<% render 'layouts/popupforms' %>
<body id = 'top'>
  

   
	<%= yield %>
</body>

</html>

app/views/layouts/form.html.erb
<!doctype html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
	<link rel="apple-touch-icon" sizes="76x76" href="assets/img/favicon.ico">

	<title>Create CV</title>

	<meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0' name='viewport' />
    <meta name="viewport" content="width=device-width" />

	<link rel="apple-touch-icon" sizes="76x76" href="assets/img/apple-icon.png" />
	<link rel="icon" type="image/png" href="assets/img/favicon.png" />

	<!--     Fonts and icons     -->
	<link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Roboto+Slab:400,700|Material+Icons" />

	<!-- CSS Files -->
	<%= stylesheet_link_tag    params[:controller], media: 'all', 'data-turbolinks-track': 'reload' %>

<%= csrf_meta_tags %>
	<%= stylesheet_link_tag    'cv_form/form', media: 'all', 'data-turbolinks-track': 'reload' %>
	

	</head>

	<body>
	    <% unless current_user %>
      <%= render 'layouts/register_warning' %>
    <% end %>
	  <%= render 'layouts/popupforms' %>
	<%= render 'layouts/nav' %>


		<div class="image-container set-full-height" >
	    <!--   Material Resume Branding   -->
	    <a href="http://creative-tim.com">
	         <div class="logo-container">
	            <div class="logo">
	                <%= image_tag 'cv/new_logo.png' %>
	            </div>
	            <div class="brand">
	                Material Resume
	            </div>
	        </div>
	    </a>
	    <%= yield %>
	    

	    <div class="footer">
	        <div class="container text-center">
	             Made with <i class="fa fa-heart heart"></i> by <a href="javascript:void(0)">Material Resume</a>.
	        </div>
	    </div>
	</div>
	</body>
	<%= javascript_include_tag 'cv_form/form', 'data-turbolinks-track': 'reload' %>
	<% javascript_include_tag params[:controller], 'data-turbolinks-track': 'reload' %>



	</html>